---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/thecodo3/public_html/src/
    - /bin/cp -R contents $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R ajax.php $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH